import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.implicitly_wait(20)
driver.execute_script("window.scrollBy(0, 600);")
SeleniumRuby_btn = driver.find_element_by_css_selector(".post-160 .woocommerce-LoopProduct-link > h3")
SeleniumRuby_btn.click()
Reviews = driver.find_element_by_css_selector(".reviews_tab > a")
Reviews.click()
driver.execute_script("window.scrollBy(0, 700);")
Stars = driver.find_element_by_css_selector(".stars > span > .star-5")
Stars.click()
Review = driver.find_element_by_id("comment")
Review.send_keys("Nice book!")
Name = driver.find_element_by_id("author")
Name.send_keys("Evgenia")
Email = driver.find_element_by_id("email")
Email.send_keys("martynova.ev1991@gmail.com")
Submit = driver.find_element_by_tag_name("[name='submit']")
Submit.click()
